<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE ProvisioningTransaction PUBLIC "sailpoint.dtd" "sailpoint.dtd">
<ProvisioningTransaction accountDisplayName="CN=Ad User1,OU=People,OU=Demo,DC=Eshiam,DC=com" applicationName="Active- Directory" identityDisplayName="Ad User1" identityName="Ad User1" integration="Active- Directory" name="0000000133" nativeIdentity="CN=Ad User1,OU=People,OU=Demo,DC=Eshiam,DC=com" operation="Create" source="IdentityRefresh" status="Failed" type="Auto">
  <Attributes>
    <Map>
      <entry key="request">
        <value>
          <AccountRequest application="Active- Directory" assignmentIds="2e5e17870e314fe0bc20a952f991aa31" nativeIdentity="CN=Ad User1,OU=People,OU=Demo,DC=Eshiam,DC=com" op="Create">
            <Attributes>
              <Map>
                <entry key="provisioningTransactionId" value="c0a8010384811d0f8184853562190494"/>
              </Map>
            </Attributes>
            <AttributeRequest name="memberOf" op="Add" value="CN=manual Testing,OU=Groups,OU=Demo,DC=Eshiam,DC=com"/>
            <AttributeRequest name="objectType" op="Set" value="User"/>
            <AttributeRequest name="sAMAccountName" op="Set" value="Ad User1"/>
            <AttributeRequest name="password" op="Set">
              <Attributes>
                <Map>
                  <entry key="secret" value="true"/>
                </Map>
              </Attributes>
            </AttributeRequest>
            <AttributeRequest name="IIQDisabled" op="Set">
              <Value>
                <Boolean/>
              </Value>
            </AttributeRequest>
            <AttributeRequest name="givenName" op="Set" value="Ad"/>
            <AttributeRequest name="sn" op="Set" value="User1"/>
            <AttributeRequest name="employeeId" op="Set" value="adUser01"/>
            <AttributeRequest name="msNPAllowDialin" op="Set" value="Not Set"/>
            <ProvisioningResult status="failed">
              <Errors>
                <Message key="Exception occurred while executing the RPCRequest: Errors returned from IQService. &quot;The object already exists. 00000524: UpdErr: DSID-031A1261, problem 6005 (ENTRY_EXISTS), data 0 . HRESULT:[0x80071392] For identity: CN=Ad User1,OU=People,OU=Demo,DC=Eshiam,DC=com&quot;" type="Error"/>
              </Errors>
            </ProvisioningResult>
          </AccountRequest>
        </value>
      </entry>
    </Map>
  </Attributes>
</ProvisioningTransaction>